### ISSUE TITLE
corrupted buffer

### ISSUE THREAD

**Issue by DeoLeung** [rycus86/prometheus_flask_exporter#59]
seems to be problem of the low level library, shall this library handle this exception?

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prometheus_flask_exporter/__init__.py", line 567, in func
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prometheus_flask_exporter/__init__.py", line 635, in func
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prometheus_flask_exporter/__init__.py", line 219, in prometheus_metrics
    return generate_latest(registry), 200, headers
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 106, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 82, in collect
    for metric in collector.collect():
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/multiprocess.py", line 149, in collect
    return self.merge(files, accumulate=True)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/multiprocess.py", line 41, in merge
    metrics = MultiProcessCollector._read_metrics(files)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/multiprocess.py", line 61, in _read_metrics
    file_values = MmapedDict.read_all_values_from_file(f)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/mmap_dict.py", line 87, in read_all_values_from_file
    used = _unpack_integer(data, 0)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)
```

maybe happen because we use docker to run our flask app, since writing files to disk invoke a lot of disk io
we map the folder into `tmpfs`

```yml
  environment: 
    prometheus_multiproc_dir: /tmp
  tmpfs:
    - /tmp
```

**Comment by rycus86** [comment]
Thanks for reporting this! It does seem like a problem with mmap (maybe) in the underlying library.

Does this happen all the time? At the start or later? Can you check if you `/tmp` is running out of space perhaps? I think Docker gives you something small like 64MB by default if I remember correctly.

**Comment by DeoLeung** [comment]
it happens later, and just once last few months, I restarted the process.

I will have a look at the tmpfs size if it happens again.

**Comment by rycus86** [comment]
Closing this issue for now, but feel free to reopen (or open a new issue) if you have any new information!

**Comment by DeoLeung** [comment]
encountered this again, and I think I found the cause.

we have a 2gb mem limit over the container, when the process reach the limit, docker restarts the container.
however, after restarting, the `*.db` files are not cleaned up, if the restarts happened to be very frequently, soom the stale files will reach around `24mb` then this exception is raised

**Comment by rycus86** [comment]
Thanks a lot for the report!
Hm, so you don't get a new container, only the existing one gets restarted? That would explain it, yeah.
You could potentially try giving your containers a tmpfs mount and pointing the Prometheus tmpdir there? You probably know best how to resolve it though. 🙂
