### ISSUE TITLE
Prometheus service not going up

### ISSUE THREAD

**Issue by maxclac** [rycus86/prometheus_flask_exporter#96]
Hi!

I am trying the sample-signals example and it seems that my prometheus service does not come up for some reason.
```
docker-compose ps
           Name                          Command               State            Ports         
----------------------------------------------------------------------------------------------
sample-signals_app_1          /bin/sh -c python /var/ser ...   Up       0.0.0.0:5000->5000/tcp
sample-signals_generator_1    /bin/sh -c python /var/app ...   Up                             
sample-signals_grafana_1      /run.sh                          Up       0.0.0.0:3000->3000/tcp
sample-signals_prometheus_1   /bin/prometheus --config.f ...   Exit 2
```
Here are the logs:

```
docker-compose logs prometheus
Attaching to sample-signals_prometheus_1
prometheus_1  | level=info ts=2021-04-06T08:48:32.219308157Z caller=main.go:220 msg="Starting Prometheus" version="(version=2.2.1, branch=HEAD, revision=bc6058c81272a8d938c05e75607371284236aadc)"
prometheus_1  | level=info ts=2021-04-06T08:48:32.220676771Z caller=main.go:221 build_context="(go=go1.10, user=root@149e5b3f0829, date=20180314-14:15:45)"
prometheus_1  | level=info ts=2021-04-06T08:48:32.220730262Z caller=main.go:222 host_details="(Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 bcd9f19a07fd (none))"
prometheus_1  | level=info ts=2021-04-06T08:48:32.220755953Z caller=main.go:223 fd_limits="(soft=1048576, hard=1048576)"
prometheus_1  | level=info ts=2021-04-06T08:48:32.223453859Z caller=main.go:504 msg="Starting TSDB ..."
prometheus_1  | level=info ts=2021-04-06T08:48:32.223768047Z caller=web.go:382 component=web msg="Start listening for connections" address=0.0.0.0:9090
prometheus_1  | level=info ts=2021-04-06T08:48:32.239008644Z caller=main.go:514 msg="TSDB started"
prometheus_1  | level=info ts=2021-04-06T08:48:32.239070015Z caller=main.go:588 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
prometheus_1  | level=info ts=2021-04-06T08:48:32.239440582Z caller=main.go:491 msg="Server is ready to receive web requests."
prometheus_1  | panic: runtime error: slice bounds out of range
prometheus_1  | 
prometheus_1  | goroutine 45 [running]:
prometheus_1  | github.com/prometheus/prometheus/vendor/github.com/miekg/dns.ClientConfigFromFile(0x1ae9f8a, 0x10, 0x0, 0x0, 0x0)
prometheus_1  |         /go/src/github.com/prometheus/prometheus/vendor/github.com/miekg/dns/clientconfig.go:86 +0x9c4
prometheus_1  | github.com/prometheus/prometheus/discovery/dns.lookupWithSearchPath(0xc420352845, 0x3, 0xc4201e0001, 0x1c37240, 0xc420fb19e0, 0xc4201c74a0, 0xc4201eafc8, 0x149bc12)
prometheus_1  |         /go/src/github.com/prometheus/prometheus/discovery/dns/dns.go:246 +0x48
prometheus_1  | github.com/prometheus/prometheus/discovery/dns.(*Discovery).refresh(0xc42007db80, 0x1c50d80, 0xc42007dbc0, 0xc420352845, 0x3, 0xc42024ca80, 0x8000000000000000, 0x3)
prometheus_1  |         /go/src/github.com/prometheus/prometheus/discovery/dns/dns.go:174 +0x73
prometheus_1  | github.com/prometheus/prometheus/discovery/dns.(*Discovery).refreshAll.func1(0xc42007db80, 0x1c50d80, 0xc42007dbc0, 0xc42024ca80, 0xc4204d2050, 0xc420352845, 0x3)
prometheus_1  |         /go/src/github.com/prometheus/prometheus/discovery/dns/dns.go:163 +0x70
prometheus_1  | created by github.com/prometheus/prometheus/discovery/dns.(*Discovery).refreshAll
prometheus_1  |         /go/src/github.com/prometheus/prometheus/discovery/dns/dns.go:162 +0xd3
```

And of course nothing is displayed on Grafana:

![Grafana](https://user-images.githubusercontent.com/32101438/113685708-0bbbbf80-96b6-11eb-9759-4d58744b8718.png)

What is going on?

Best regards

**Comment by rycus86** [comment]
Hi @maxclac

I'm guessing that the Prometheus configuration I have in this repo is no longer compatible with the last Prometheus version. :(
I'm not super sure, will have to check when I get some time in the next week or so. It could also be Docker compose changing something potentially if it's complaining about DNS related problems.

**Comment by maxclac** [comment]
Simple fix: I used the latest version of the image instead of the v2.2.1 already existing in the docker-compose.yml file. It seems to work now.
